= The Curse of Vampyrism
SneakyAlba
Pre-Alpha Design Doc
:icons: font

****
WARNING: This page represents an unimplemented system. It is a declaration of
intent and not reflective of any current, future, or final implementation.
****

[quote, Unknown, Observations of an Immortal]
____
In death; the spirit fades, the body corrupts, and the soul preserves.

What, then, should the soul corrupt and the body preserve?

In the hands of the magician: Something both great and _terrible_ ...
____

== Un-life Under Vampyrism

Vampyrism is a _Curse_ which affects humanoid entities, transforming them into
an insatiable, obsessive-compulsive incarnation of _appetite_.

Those with the curse are afflicted as follows:

.Pros:
- They become functionally *immortal*
- They can no longer drown nor suffocate
- When injured, their health passively recovers up to their current hunger level

.Neutral:
- They are now considered *undead*
- They can be targeted by additional rites, rituals, and spells; and may now be
affected by others differently

.Cons:
- They must feed on the living to sate their hunger
- They become *_Vulnerable_* when exposed to sunlight or garlic; when submerged
in water; or while caught on fire
- They cannot cross lines of salt nor bodies of water
- They are immune to *_Fire Resistance_*

[NOTE]
====
*_Vulnerable_* _entities receive more physical damage. When applied alongside
an equivalent level of_ *_Resistance_*, _their effects cancel out._

_Immortality is not invulnerability; and thus vampyres can still be slain using
magic, by powerful Infernals and bosses, and are mortal while_ *_Vulnerable_*.
====

== Encountering the Vampyre

Vampyres can be found roaming any biome where villages might be settled, but
have only been sighted under new moons whence they are furthest from sunlight.

Despite their immortality, the life expectancy of a vampyre is fleeting. While
they're certainly more dangerous than the average monster, few survive long
enough to take charge over their new state of being.

Legends amidst some villages, however, speak of terrible dark magicians who have
drank from the sleeping and stolen away children for generations ...

== Sources of Vampyrism

NOTE: This section is a stub, and each method listed deserves a section with a
full-bodied description and steps.

- Embrace the gifts of a dark sire
- Survive lethal damage from a vampyre with the *_Bad Omen_* effect
- Make compact with an Infernal
- Enter the servitude of a higher power
- Be subjected to an especially powerful bewitchment
