= Immersive Incantations API: How do Vampyres work?
SneakyAlba
Pre-Alpha Design Docs
:toc: left

== Features

=== Vampyres can suck blood!

==== What do I want?

Vampyres can drain players and living entities of blood, replenishing their own
pool of blood if not full. "Living" for this effect should only inlcude farm
animals and villagers/pillagers/witches by default, but be modifiable through
taglists and datapacks to include or exclude specific entities as desired.

Only the intelligent creatures such as villagers/pillagers/witches will have a
blood meter of their own, other valid targets will simply take damage each time
they are fed on by the vampyre. This too will be controllable through datapacks.

Damage will be dealt to all entities that are fed on by default unless asleep,
and this property should be togglable via config files. If the damage is
configured to be less than zero, this feature is disabled.

Draining too much blood will also cause the entity to take damage, with the
amount needed drained and the damage being dealt again configurable through the
config files. Setting the damage to less than zero disables this feature.

Vampyres should also have an accelerating feeding effect by default, causing the
rate at which they drain to increase after each blood unit taken until a timed
interval passes. How many increments, how quickly each speed is reached and
lost, and what speed each increment feeds at should probably be configurable
through a datapack asset file.

Unlike feeding on food items, vampyres should not be "stopped" when the meter is
full, the units of blood consumed are just wasted.

Blood given to the feeding vampyre does not scale with the blood taken, and by
default should restore an amount determined by what is being fed upon, with
intelligent creatures like villagers/pillagers/witches restoring more than
livestock, and with an added bonus for each level a villager has and their
reputation with the vampyre.

Damage taken from feeding may have to be it's own damage type for mod and update
compatibility purposes. The resource shouldn't be referred to as blood in
gameplay as to align with Mojang's own no blood references policy and better fit
into the vanilla experience.

==== Why do I want it?

Feeding upon the living is *the* staple feature of a vampire that sets it apart
from most other undead, spirits, and demons; there's simply no way this could be
adapted without the quintessential property that makes a vampire a vampire.

But even just for themeatic purposes these _vampyres_ are intended to be hunger
and obsesion incarnate, and making this feature is an extension of that theme.
This is also why the feeding accelerates by default; it lets me both build that
theme further and adapt the "vampire cannot stop themselves once they start"
trope.

Further building onto the relentless hunger themeing, it then also makes sense
that you can drink regardless of the status of your blood meter, risking waste
if not properly managed.

The enhanced feeding on sleeping targets at night is partly to help build that
folklore-y vibe and partly to help out less technically inclined players who may
not want to go through the effort of caging up villagers in trading posts. It
works as a vampire trope for good reason.

==== How can I most easily achieve what I want?

NOTE: Todo

=== Hunger is restored using blood; not food

==== What do I want?

Vampyres should not be able to gain hunger or saturation from any source other
than their internal blood meter.

Restoring lost hunger should occur when the vampyre sleeps in their coffin, with
each hunger point roughly restoring at the same rate air bubbles would be lost
when a living creature is underwater. Blood is consumed in order to restore each
point of hunger, with the amounts configurable through the mod config files.

Upon wake, the vampyre's blood meter is reset to empty by default, and this can
be disabled through the config files.

==== Why do I want it?

This is another half of the core element of vampirism; they _must_ feed upon the
living to sate themselves. However, splitting the restoring from the feeding
itself can allow for some more tropes to be adapted, like the need to return to
their grave each night.

We again build on the appetite theme by having *_all_* blood be consumed on
rest, meaning a vampire player is encouraged to feed each night or else stay
awake through the day and risk being stuck without a safe way of returning home,
potentially succumbing to hunger, or be caught without a way to properly heal.
